- name: Python Code Style, Quality, and Lint
  # You may pin to the exact commit or the version.
  # uses: weibullguy/python-lint-plus@62231462dd6b1e0e560bfdae6422d1c8baa4ea4b
  uses: weibullguy/python-lint-plus@v1.6.0
  with:
    # A list of all paths to test
    python-root-list: # optional, default is .
    # Use Black
    use-black: true
    # Use yapf
    use-yapf: # optional
    # Use isort
    use-isort: # optional, default is true
    # Use docformatter
    use-docformatter: # optional, default is true
    # Use pycodestyle
    use-pycodestyle: # optional, default is true
    # Use pydocstyle
    use-pydocstyle: # optional, default is true
    # Use mypy
    use-mypy: # optional, default is true
    # Use Pylint
    use-pylint: # optional, default is true
    # Use Flake8
    use-flake8: # optional, default is true
    # Use mccabe
    use-mccabe: # optional
    # Use radon
    use-radon: # optional
    # Use rstcheck
    use-rstcheck: # optional, default is true
    # Use check-manifest
    use-check-manifest: # optional, default is true
    # Use pyroma
    use-pyroma: # optional, default is true
    # Extra options: black --check $(extra-black-options) $(python-root-list)
    extra-black-options: # optional, default is 
    # Extra options: yapf $(extra-yapf-optsion) $(python-root-list)
    extra-yapf-options: # optional, default is 
    # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff 
    extra-isort-options: # optional, default is 
    # Extra options: docformatter $(extra-docformatter-options) $(python-root-list)
    extra-docformatter-options: # optional, default is 
    # Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)
    extra-pycodestyle-options: # optional, default is 
    # Extra options: pydocstyle $(extra-pydocstyle-options) $(python-root-list)
    extra-pydocstyle-options: # optional, default is 
    # Extra options: mypy $(extra-mypy-options) $(python-root-list)
    extra-mypy-options: # optional, default is 
    # Extra options: pylint $(extra-pylint-options) $(python-root-list)
    extra-pylint-options: # optional, default is 
    # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
    extra-flake8-options: # optional, default is 
    # Extra options: python -m mccabe $(extra-mccabe-options) $(python-root-list)
    extra-mccabe-options: # optional, default is 
    # Extra options: radon $(extra-radon-options) $(python-root-list)
    extra-radon-options: # optional, default is 
    # Extra options: rstcheck $(extra-rstcheck-options) $(python-root-list)
    extra-rstcheck-options: # optional, default is 
    # Extra options: check-manifest $(extra-manifest-options) .
    extra-manifest-options: # optional, default is 
    # Extra options: pyroma $(extra-manifest-options) .
    extra-pyroma-options: # optional, default is 
